# Generated by Django 5.0.3 on 2024-03-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_status',
            field=models.BooleanField(default=False),
        ),
    ]
