# Generated by Django 5.0.3 on 2024-03-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_price_course_orignal_price_course_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=51),
        ),
    ]
