# Generated by Django 5.0.3 on 2024-03-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lecture_duration_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_lectures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
