# Generated by Django 5.0.3 on 2024-03-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_total_lectures_alter_lecture_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
