# Generated by Django 5.0.3 on 2024-04-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.TextField(default='No'),
        ),
        migrations.AddField(
            model_name='category',
            name='num_courses',
            field=models.IntegerField(default=0),
        ),
    ]
