# Generated by Django 5.0.3 on 2024-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_category_icon_category_num_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
