# Generated by Django 5.0.3 on 2024-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_review',
            field=models.IntegerField(default=0),
        ),
    ]
