# Generated by Django 5.0.3 on 2024-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
