# Generated by Django 5.0.3 on 2024-05-04 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_student_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
