# Generated by Django 5.0.3 on 2024-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='SEO_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
